# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1912, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonframe = QtWidgets.QFrame(self.centralwidget)
        self.buttonframe.setGeometry(QtCore.QRect(1630, 10, 271, 1021))
        self.buttonframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonframe.setObjectName("buttonframe")
        self.browseButton = QtWidgets.QPushButton(self.buttonframe)
        self.browseButton.setGeometry(QtCore.QRect(20, 60, 211, 31))
        self.browseButton.setObjectName("browseButton")
        self.retinaButton = QtWidgets.QCheckBox(self.buttonframe)
        self.retinaButton.setGeometry(QtCore.QRect(40, 180, 171, 31))
        self.retinaButton.setChecked(False)
        self.retinaButton.setObjectName("retinaButton")
        self.metadata = QtWidgets.QTableView(self.buttonframe)
        self.metadata.setGeometry(QtCore.QRect(20, 361, 211, 341))
        self.metadata.setAlternatingRowColors(True)
        self.metadata.setShowGrid(False)
        self.metadata.setGridStyle(QtCore.Qt.SolidLine)
        self.metadata.setWordWrap(True)
        self.metadata.setCornerButtonEnabled(False)
        self.metadata.setObjectName("metadata")
        self.metadata.horizontalHeader().setVisible(False)
        self.metadata.verticalHeader().setVisible(False)
        self.browseFolderButton = QtWidgets.QPushButton(self.buttonframe)
        self.browseFolderButton.setGeometry(QtCore.QRect(20, 100, 211, 31))
        self.browseFolderButton.setObjectName("browseFolderButton")
        self.deleteButton = QtWidgets.QPushButton(self.buttonframe)
        self.deleteButton.setGeometry(QtCore.QRect(30, 810, 201, 31))
        self.deleteButton.setObjectName("deleteButton")
        self.saveButton = QtWidgets.QPushButton(self.buttonframe)
        self.saveButton.setGeometry(QtCore.QRect(30, 850, 201, 31))
        self.saveButton.setObjectName("saveButton")
        self.exportButton = QtWidgets.QPushButton(self.buttonframe)
        self.exportButton.setGeometry(QtCore.QRect(60, 900, 151, 31))
        self.exportButton.setObjectName("exportButton")
        self.infoLabel = QtWidgets.QLabel(self.buttonframe)
        self.infoLabel.setGeometry(QtCore.QRect(20, 220, 211, 71))
        self.infoLabel.setAutoFillBackground(True)
        self.infoLabel.setText("")
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.generateButton = QtWidgets.QPushButton(self.buttonframe)
        self.generateButton.setEnabled(False)
        self.generateButton.setGeometry(QtCore.QRect(20, 320, 211, 31))
        self.generateButton.setCheckable(False)
        self.generateButton.setChecked(False)
        self.generateButton.setAutoRepeat(False)
        self.generateButton.setDefault(False)
        self.generateButton.setObjectName("generateButton")
        self.buttonframe_2 = QtWidgets.QFrame(self.buttonframe)
        self.buttonframe_2.setGeometry(QtCore.QRect(10, -940, 271, 951))
        self.buttonframe_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonframe_2.setObjectName("buttonframe_2")
        self.browseButton_2 = QtWidgets.QPushButton(self.buttonframe_2)
        self.browseButton_2.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.browseButton_2.setObjectName("browseButton_2")
        self.metadata_2 = QtWidgets.QTableView(self.buttonframe_2)
        self.metadata_2.setGeometry(QtCore.QRect(10, 190, 241, 651))
        self.metadata_2.setAlternatingRowColors(True)
        self.metadata_2.setShowGrid(False)
        self.metadata_2.setGridStyle(QtCore.Qt.SolidLine)
        self.metadata_2.setWordWrap(True)
        self.metadata_2.setCornerButtonEnabled(False)
        self.metadata_2.setObjectName("metadata_2")
        self.metadata_2.horizontalHeader().setVisible(False)
        self.metadata_2.verticalHeader().setVisible(False)
        self.browseFolderButton_2 = QtWidgets.QPushButton(self.buttonframe_2)
        self.browseFolderButton_2.setGeometry(QtCore.QRect(20, 70, 231, 41))
        self.browseFolderButton_2.setObjectName("browseFolderButton_2")
        self.deleteButton_3 = QtWidgets.QPushButton(self.buttonframe_2)
        self.deleteButton_3.setGeometry(QtCore.QRect(30, 860, 89, 31))
        self.deleteButton_3.setObjectName("deleteButton_3")
        self.saveButton_2 = QtWidgets.QPushButton(self.buttonframe_2)
        self.saveButton_2.setGeometry(QtCore.QRect(160, 860, 89, 31))
        self.saveButton_2.setObjectName("saveButton_2")
        self.exportButton_2 = QtWidgets.QPushButton(self.buttonframe_2)
        self.exportButton_2.setGeometry(QtCore.QRect(60, 900, 151, 31))
        self.exportButton_2.setObjectName("exportButton_2")
        self.infoLabel_2 = QtWidgets.QLabel(self.buttonframe_2)
        self.infoLabel_2.setGeometry(QtCore.QRect(20, 170, 211, 51))
        self.infoLabel_2.setText("")
        self.infoLabel_2.setWordWrap(True)
        self.infoLabel_2.setObjectName("infoLabel_2")
        self.generateButton_2 = QtWidgets.QPushButton(self.buttonframe_2)
        self.generateButton_2.setEnabled(False)
        self.generateButton_2.setGeometry(QtCore.QRect(30, 140, 211, 31))
        self.generateButton_2.setCheckable(False)
        self.generateButton_2.setChecked(False)
        self.generateButton_2.setAutoRepeat(False)
        self.generateButton_2.setDefault(False)
        self.generateButton_2.setObjectName("generateButton_2")
        self.labelRecording_2 = QtWidgets.QLabel(self.buttonframe)
        self.labelRecording_2.setGeometry(QtCore.QRect(10, 0, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelRecording_2.setFont(font)
        self.labelRecording_2.setObjectName("labelRecording_2")
        self.produceCorticalButton = QtWidgets.QPushButton(self.buttonframe)
        self.produceCorticalButton.setGeometry(QtCore.QRect(30, 760, 201, 31))
        self.produceCorticalButton.setObjectName("produceCorticalButton")
        self.produceBackprojectedButton = QtWidgets.QPushButton(self.buttonframe)
        self.produceBackprojectedButton.setGeometry(QtCore.QRect(30, 720, 201, 31))
        self.produceBackprojectedButton.setObjectName("produceBackprojectedButton")
        self.maintabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.maintabWidget.setGeometry(QtCore.QRect(10, 0, 1611, 1021))
        self.maintabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.maintabWidget.setObjectName("maintabWidget")
        self.mainpage = QtWidgets.QWidget()
        self.mainpage.setObjectName("mainpage")
        self.dataframe = QtWidgets.QFrame(self.mainpage)
        self.dataframe.setGeometry(QtCore.QRect(0, 0, 1611, 1011))
        self.dataframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe.setObjectName("dataframe")
        self.videoframe = QtWidgets.QFrame(self.dataframe)
        self.videoframe.setGeometry(QtCore.QRect(-10, 40, 1611, 851))
        self.videoframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe.setObjectName("videoframe")
        self.label = QtWidgets.QLabel(self.videoframe)
        self.label.setGeometry(QtCore.QRect(200, 30, 480, 360))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.focalLabel = QtWidgets.QLabel(self.videoframe)
        self.focalLabel.setGeometry(QtCore.QRect(200, 430, 480, 360))
        self.focalLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.focalLabel.setText("")
        self.focalLabel.setObjectName("focalLabel")
        self.corticalLabel = QtWidgets.QLabel(self.videoframe)
        self.corticalLabel.setGeometry(QtCore.QRect(930, 430, 480, 360))
        self.corticalLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.corticalLabel.setText("")
        self.corticalLabel.setObjectName("corticalLabel")
        self.recordButton = QtWidgets.QPushButton(self.videoframe)
        self.recordButton.setGeometry(QtCore.QRect(750, 310, 141, 51))
        self.recordButton.setObjectName("recordButton")
        self.stopRecordButton = QtWidgets.QPushButton(self.videoframe)
        self.stopRecordButton.setGeometry(QtCore.QRect(920, 310, 141, 51))
        self.stopRecordButton.setObjectName("stopRecordButton")
        self.labelRecording = QtWidgets.QLabel(self.videoframe)
        self.labelRecording.setGeometry(QtCore.QRect(1090, 290, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelRecording.setFont(font)
        self.labelRecording.setObjectName("labelRecording")
        self.checkUnedited = QtWidgets.QCheckBox(self.videoframe)
        self.checkUnedited.setGeometry(QtCore.QRect(770, 260, 70, 17))
        self.checkUnedited.setObjectName("checkUnedited")
        self.checkBackprojected = QtWidgets.QCheckBox(self.videoframe)
        self.checkBackprojected.setGeometry(QtCore.QRect(860, 260, 91, 17))
        self.checkBackprojected.setObjectName("checkBackprojected")
        self.checkRetina = QtWidgets.QCheckBox(self.videoframe)
        self.checkRetina.setGeometry(QtCore.QRect(980, 260, 101, 17))
        self.checkRetina.setObjectName("checkRetina")
        self.xspinBox = QtWidgets.QSpinBox(self.videoframe)
        self.xspinBox.setGeometry(QtCore.QRect(850, 150, 42, 22))
        self.xspinBox.setMaximum(480)
        self.xspinBox.setProperty("value", 240)
        self.xspinBox.setObjectName("xspinBox")
        self.yspinBox = QtWidgets.QSpinBox(self.videoframe)
        self.yspinBox.setGeometry(QtCore.QRect(850, 200, 42, 22))
        self.yspinBox.setMaximum(360)
        self.yspinBox.setProperty("value", 180)
        self.yspinBox.setObjectName("yspinBox")
        self.label_8 = QtWidgets.QLabel(self.videoframe)
        self.label_8.setGeometry(QtCore.QRect(750, 150, 81, 16))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.videoframe)
        self.label_12.setGeometry(QtCore.QRect(750, 200, 81, 16))
        self.label_12.setObjectName("label_12")
        self.scrubframe = QtWidgets.QFrame(self.dataframe)
        self.scrubframe.setGeometry(QtCore.QRect(10, 850, 1611, 151))
        self.scrubframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe.setObjectName("scrubframe")
        self.scrubframe_3 = QtWidgets.QFrame(self.scrubframe)
        self.scrubframe_3.setGeometry(QtCore.QRect(-10, 0, 1591, 161))
        self.scrubframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_3.setObjectName("scrubframe_3")
        self.scrubSlider = QtWidgets.QSlider(self.scrubframe_3)
        self.scrubSlider.setGeometry(QtCore.QRect(49, 10, 1461, 22))
        self.scrubSlider.setTracking(False)
        self.scrubSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scrubSlider.setObjectName("scrubSlider")
        self.frameNum = QtWidgets.QLCDNumber(self.scrubframe_3)
        self.frameNum.setGeometry(QtCore.QRect(1530, 10, 31, 23))
        self.frameNum.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameNum.setSmallDecimalPoint(False)
        self.frameNum.setDigitCount(4)
        self.frameNum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.frameNum.setObjectName("frameNum")
        self.pauseButton = QtWidgets.QPushButton(self.scrubframe_3)
        self.pauseButton.setGeometry(QtCore.QRect(830, 40, 89, 29))
        self.pauseButton.setCheckable(False)
        self.pauseButton.setObjectName("pauseButton")
        self.startButton = QtWidgets.QPushButton(self.scrubframe_3)
        self.startButton.setGeometry(QtCore.QRect(730, 40, 89, 29))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.skipBackButton = QtWidgets.QToolButton(self.scrubframe_3)
        self.skipBackButton.setGeometry(QtCore.QRect(630, 40, 89, 25))
        self.skipBackButton.setArrowType(QtCore.Qt.LeftArrow)
        self.skipBackButton.setObjectName("skipBackButton")
        self.skipForwardButton = QtWidgets.QToolButton(self.scrubframe_3)
        self.skipForwardButton.setGeometry(QtCore.QRect(930, 40, 89, 25))
        self.skipForwardButton.setArrowType(QtCore.Qt.RightArrow)
        self.skipForwardButton.setObjectName("skipForwardButton")
        self.skipBackButton_3 = QtWidgets.QToolButton(self.scrubframe_3)
        self.skipBackButton_3.setGeometry(QtCore.QRect(530, 40, 89, 25))
        self.skipBackButton_3.setAutoRaise(False)
        self.skipBackButton_3.setArrowType(QtCore.Qt.NoArrow)
        self.skipBackButton_3.setObjectName("skipBackButton_3")
        self.skipForwardButton3 = QtWidgets.QToolButton(self.scrubframe_3)
        self.skipForwardButton3.setGeometry(QtCore.QRect(1030, 40, 89, 25))
        self.skipForwardButton3.setArrowType(QtCore.Qt.NoArrow)
        self.skipForwardButton3.setObjectName("skipForwardButton3")
        self.maintabWidget.addTab(self.mainpage, "")
        self.focuspage = QtWidgets.QWidget()
        self.focuspage.setObjectName("focuspage")
        self.biglabel = QtWidgets.QLabel(self.focuspage)
        self.biglabel.setGeometry(QtCore.QRect(160, 80, 1280, 720))
        self.biglabel.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.biglabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.biglabel.setText("")
        self.biglabel.setObjectName("biglabel")
        self.scrubframe_2 = QtWidgets.QFrame(self.focuspage)
        self.scrubframe_2.setGeometry(QtCore.QRect(0, 850, 1611, 161))
        self.scrubframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrubframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_2.setObjectName("scrubframe_2")
        self.scrubSlider_2 = QtWidgets.QSlider(self.scrubframe_2)
        self.scrubSlider_2.setGeometry(QtCore.QRect(19, 10, 1531, 22))
        self.scrubSlider_2.setMaximum(999999999)
        self.scrubSlider_2.setTracking(False)
        self.scrubSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.scrubSlider_2.setObjectName("scrubSlider_2")
        self.frameNum_2 = QtWidgets.QLCDNumber(self.scrubframe_2)
        self.frameNum_2.setGeometry(QtCore.QRect(1560, 10, 31, 23))
        self.frameNum_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameNum_2.setSmallDecimalPoint(False)
        self.frameNum_2.setDigitCount(4)
        self.frameNum_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.frameNum_2.setObjectName("frameNum_2")
        self.pauseButton_2 = QtWidgets.QPushButton(self.scrubframe_2)
        self.pauseButton_2.setGeometry(QtCore.QRect(830, 40, 89, 29))
        self.pauseButton_2.setCheckable(False)
        self.pauseButton_2.setObjectName("pauseButton_2")
        self.startButton_2 = QtWidgets.QPushButton(self.scrubframe_2)
        self.startButton_2.setGeometry(QtCore.QRect(730, 40, 89, 29))
        self.startButton_2.setCheckable(False)
        self.startButton_2.setObjectName("startButton_2")
        self.skipBackButton_2 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipBackButton_2.setGeometry(QtCore.QRect(630, 40, 89, 25))
        self.skipBackButton_2.setArrowType(QtCore.Qt.LeftArrow)
        self.skipBackButton_2.setObjectName("skipBackButton_2")
        self.skipForwardButton_2 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipForwardButton_2.setGeometry(QtCore.QRect(930, 40, 89, 25))
        self.skipForwardButton_2.setArrowType(QtCore.Qt.RightArrow)
        self.skipForwardButton_2.setObjectName("skipForwardButton_2")
        self.skipBackButton_4 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipBackButton_4.setGeometry(QtCore.QRect(530, 40, 89, 25))
        self.skipBackButton_4.setAutoRaise(False)
        self.skipBackButton_4.setArrowType(QtCore.Qt.NoArrow)
        self.skipBackButton_4.setObjectName("skipBackButton_4")
        self.skipForwardButton_4 = QtWidgets.QToolButton(self.scrubframe_2)
        self.skipForwardButton_4.setGeometry(QtCore.QRect(1030, 40, 89, 25))
        self.skipForwardButton_4.setArrowType(QtCore.Qt.NoArrow)
        self.skipForwardButton_4.setObjectName("skipForwardButton_4")
        self.delaySpinBox = QtWidgets.QDoubleSpinBox(self.scrubframe_2)
        self.delaySpinBox.setGeometry(QtCore.QRect(200, 70, 62, 22))
        self.delaySpinBox.setDecimals(1)
        self.delaySpinBox.setMinimum(0.5)
        self.delaySpinBox.setSingleStep(0.1)
        self.delaySpinBox.setProperty("value", 1.0)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.label_2 = QtWidgets.QLabel(self.scrubframe_2)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 151, 31))
        self.label_2.setObjectName("label_2")
        self.fixationMouseButton = QtWidgets.QCheckBox(self.scrubframe_2)
        self.fixationMouseButton.setGeometry(QtCore.QRect(50, 40, 271, 17))
        self.fixationMouseButton.setObjectName("fixationMouseButton")
        self.maintabWidget.addTab(self.focuspage, "")
        self.gallerypage = QtWidgets.QWidget()
        self.gallerypage.setObjectName("gallerypage")
        self.dataframe_2 = QtWidgets.QFrame(self.gallerypage)
        self.dataframe_2.setGeometry(QtCore.QRect(0, 0, 1621, 1011))
        self.dataframe_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dataframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataframe_2.setObjectName("dataframe_2")
        self.videoframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.videoframe_4.setGeometry(QtCore.QRect(10, 0, 1531, 1001))
        self.videoframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe_4.setObjectName("videoframe_4")
        self.a = ClickLabel(self.videoframe_4)
        self.a.setGeometry(QtCore.QRect(70, 10, 320, 180))
        self.a.setFocusPolicy(QtCore.Qt.NoFocus)
        self.a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.a.setText("")
        self.a.setObjectName("a")
        self.b = ClickLabel(self.videoframe_4)
        self.b.setGeometry(QtCore.QRect(420, 10, 320, 180))
        self.b.setFocusPolicy(QtCore.Qt.NoFocus)
        self.b.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b.setText("")
        self.b.setObjectName("b")
        self.c = ClickLabel(self.videoframe_4)
        self.c.setGeometry(QtCore.QRect(770, 10, 320, 180))
        self.c.setFocusPolicy(QtCore.Qt.NoFocus)
        self.c.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c.setText("")
        self.c.setObjectName("c")
        self.d = ClickLabel(self.videoframe_4)
        self.d.setGeometry(QtCore.QRect(1120, 10, 320, 180))
        self.d.setFocusPolicy(QtCore.Qt.NoFocus)
        self.d.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.d.setText("")
        self.d.setObjectName("d")
        self.g = ClickLabel(self.videoframe_4)
        self.g.setGeometry(QtCore.QRect(770, 250, 320, 180))
        self.g.setFocusPolicy(QtCore.Qt.NoFocus)
        self.g.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.g.setText("")
        self.g.setObjectName("g")
        self.h = ClickLabel(self.videoframe_4)
        self.h.setGeometry(QtCore.QRect(1120, 250, 320, 180))
        self.h.setFocusPolicy(QtCore.Qt.NoFocus)
        self.h.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.h.setText("")
        self.h.setObjectName("h")
        self.e = ClickLabel(self.videoframe_4)
        self.e.setGeometry(QtCore.QRect(70, 250, 320, 180))
        self.e.setFocusPolicy(QtCore.Qt.NoFocus)
        self.e.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.e.setText("")
        self.e.setObjectName("e")
        self.f = ClickLabel(self.videoframe_4)
        self.f.setGeometry(QtCore.QRect(420, 250, 320, 180))
        self.f.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f.setText("")
        self.f.setObjectName("f")
        self.l = ClickLabel(self.videoframe_4)
        self.l.setGeometry(QtCore.QRect(1120, 490, 320, 180))
        self.l.setFocusPolicy(QtCore.Qt.NoFocus)
        self.l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.l.setText("")
        self.l.setObjectName("l")
        self.i = ClickLabel(self.videoframe_4)
        self.i.setGeometry(QtCore.QRect(70, 490, 320, 180))
        self.i.setFocusPolicy(QtCore.Qt.NoFocus)
        self.i.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.i.setText("")
        self.i.setObjectName("i")
        self.k = ClickLabel(self.videoframe_4)
        self.k.setGeometry(QtCore.QRect(770, 490, 320, 180))
        self.k.setFocusPolicy(QtCore.Qt.NoFocus)
        self.k.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.k.setText("")
        self.k.setObjectName("k")
        self.j = ClickLabel(self.videoframe_4)
        self.j.setGeometry(QtCore.QRect(420, 490, 320, 180))
        self.j.setFocusPolicy(QtCore.Qt.NoFocus)
        self.j.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.j.setText("")
        self.j.setObjectName("j")
        self.o = ClickLabel(self.videoframe_4)
        self.o.setGeometry(QtCore.QRect(770, 730, 320, 180))
        self.o.setFocusPolicy(QtCore.Qt.NoFocus)
        self.o.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.o.setText("")
        self.o.setObjectName("o")
        self.m = ClickLabel(self.videoframe_4)
        self.m.setGeometry(QtCore.QRect(70, 730, 320, 180))
        self.m.setFocusPolicy(QtCore.Qt.NoFocus)
        self.m.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.m.setText("")
        self.m.setObjectName("m")
        self.p = ClickLabel(self.videoframe_4)
        self.p.setGeometry(QtCore.QRect(1120, 730, 320, 180))
        self.p.setFocusPolicy(QtCore.Qt.NoFocus)
        self.p.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p.setText("")
        self.p.setObjectName("p")
        self.n = ClickLabel(self.videoframe_4)
        self.n.setGeometry(QtCore.QRect(420, 730, 320, 180))
        self.n.setFocusPolicy(QtCore.Qt.NoFocus)
        self.n.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.n.setText("")
        self.n.setObjectName("n")
        self.numa = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numa.setGeometry(QtCore.QRect(200, 200, 61, 23))
        self.numa.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numa.setObjectName("numa")
        self.numb = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numb.setGeometry(QtCore.QRect(550, 200, 61, 23))
        self.numb.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numb.setObjectName("numb")
        self.numc = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numc.setGeometry(QtCore.QRect(900, 200, 61, 23))
        self.numc.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numc.setObjectName("numc")
        self.numd = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numd.setGeometry(QtCore.QRect(1250, 200, 61, 23))
        self.numd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numd.setObjectName("numd")
        self.numh = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numh.setGeometry(QtCore.QRect(1250, 440, 61, 23))
        self.numh.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numh.setObjectName("numh")
        self.nume = QtWidgets.QLCDNumber(self.videoframe_4)
        self.nume.setGeometry(QtCore.QRect(200, 440, 61, 23))
        self.nume.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nume.setObjectName("nume")
        self.numf = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numf.setGeometry(QtCore.QRect(550, 440, 61, 23))
        self.numf.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numf.setObjectName("numf")
        self.numg = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numg.setGeometry(QtCore.QRect(900, 440, 61, 23))
        self.numg.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numg.setObjectName("numg")
        self.numj = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numj.setGeometry(QtCore.QRect(550, 680, 61, 23))
        self.numj.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numj.setObjectName("numj")
        self.numi = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numi.setGeometry(QtCore.QRect(200, 680, 61, 23))
        self.numi.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numi.setObjectName("numi")
        self.numk = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numk.setGeometry(QtCore.QRect(900, 680, 61, 23))
        self.numk.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numk.setObjectName("numk")
        self.numl = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numl.setGeometry(QtCore.QRect(1250, 680, 61, 23))
        self.numl.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numl.setObjectName("numl")
        self.numo = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numo.setGeometry(QtCore.QRect(900, 920, 61, 23))
        self.numo.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numo.setObjectName("numo")
        self.numn = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numn.setGeometry(QtCore.QRect(550, 920, 61, 23))
        self.numn.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numn.setObjectName("numn")
        self.nump = QtWidgets.QLCDNumber(self.videoframe_4)
        self.nump.setGeometry(QtCore.QRect(1250, 920, 61, 23))
        self.nump.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.nump.setObjectName("nump")
        self.numm = QtWidgets.QLCDNumber(self.videoframe_4)
        self.numm.setGeometry(QtCore.QRect(200, 920, 61, 23))
        self.numm.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.numm.setObjectName("numm")
        self.scrubframe_4 = QtWidgets.QFrame(self.dataframe_2)
        self.scrubframe_4.setGeometry(QtCore.QRect(1540, 0, 81, 1001))
        self.scrubframe_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrubframe_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrubframe_4.setObjectName("scrubframe_4")
        self.verticalSlider_3 = QtWidgets.QSlider(self.scrubframe_4)
        self.verticalSlider_3.setGeometry(QtCore.QRect(20, 10, 22, 951))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setInvertedAppearance(True)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.maintabWidget.addTab(self.gallerypage, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(290, 50, 948, 568))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.videoView_2 = QtWidgets.QGraphicsView(self.groupBox)
        self.videoView_2.setObjectName("videoView_2")
        self.gridLayout_5.addWidget(self.videoView_2, 0, 0, 1, 1)
        self.tabs = QtWidgets.QTabWidget(self.tab)
        self.tabs.setGeometry(QtCore.QRect(127, 615, 1181, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setObjectName("tabs")
        self.controlsTab_2 = QtWidgets.QWidget()
        self.controlsTab_2.setObjectName("controlsTab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.controlsTab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cameraRadio_2 = QtWidgets.QRadioButton(self.controlsTab_2)
        self.cameraRadio_2.setChecked(True)
        self.cameraRadio_2.setObjectName("cameraRadio_2")
        self.horizontalLayout_7.addWidget(self.cameraRadio_2)
        self.cameraSpin_2 = QtWidgets.QSpinBox(self.controlsTab_2)
        self.cameraSpin_2.setObjectName("cameraSpin_2")
        self.horizontalLayout_7.addWidget(self.cameraSpin_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.videoRadio_2 = QtWidgets.QRadioButton(self.controlsTab_2)
        self.videoRadio_2.setObjectName("videoRadio_2")
        self.horizontalLayout_8.addWidget(self.videoRadio_2)
        self.videoEdit_2 = QtWidgets.QLineEdit(self.controlsTab_2)
        self.videoEdit_2.setObjectName("videoEdit_2")
        self.horizontalLayout_8.addWidget(self.videoEdit_2)
        self.browseVideoBtn_2 = QtWidgets.QPushButton(self.controlsTab_2)
        self.browseVideoBtn_2.setObjectName("browseVideoBtn_2")
        self.horizontalLayout_8.addWidget(self.browseVideoBtn_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.startBtn_2 = QtWidgets.QPushButton(self.controlsTab_2)
        self.startBtn_2.setObjectName("startBtn_2")
        self.horizontalLayout_9.addWidget(self.startBtn_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.tabs.addTab(self.controlsTab_2, "")
        self.settingsTab_2 = QtWidgets.QWidget()
        self.settingsTab_2.setObjectName("settingsTab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.settingsTab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.settingsTab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.pbFileEdit_2 = QtWidgets.QLineEdit(self.settingsTab_2)
        self.pbFileEdit_2.setText("")
        self.pbFileEdit_2.setObjectName("pbFileEdit_2")
        self.horizontalLayout_10.addWidget(self.pbFileEdit_2)
        self.pbBrowseBtn_2 = QtWidgets.QPushButton(self.settingsTab_2)
        self.pbBrowseBtn_2.setObjectName("pbBrowseBtn_2")
        self.horizontalLayout_10.addWidget(self.pbBrowseBtn_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.settingsTab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.pbtxtFileEdit_2 = QtWidgets.QLineEdit(self.settingsTab_2)
        self.pbtxtFileEdit_2.setText("")
        self.pbtxtFileEdit_2.setObjectName("pbtxtFileEdit_2")
        self.horizontalLayout_11.addWidget(self.pbtxtFileEdit_2)
        self.pbtxtBrowseBtn_2 = QtWidgets.QPushButton(self.settingsTab_2)
        self.pbtxtBrowseBtn_2.setObjectName("pbtxtBrowseBtn_2")
        self.horizontalLayout_11.addWidget(self.pbtxtBrowseBtn_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.settingsTab_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.classesFileEdit_2 = QtWidgets.QLineEdit(self.settingsTab_2)
        self.classesFileEdit_2.setText("")
        self.classesFileEdit_2.setObjectName("classesFileEdit_2")
        self.horizontalLayout_12.addWidget(self.classesFileEdit_2)
        self.classesBrowseBtn_2 = QtWidgets.QPushButton(self.settingsTab_2)
        self.classesBrowseBtn_2.setObjectName("classesBrowseBtn_2")
        self.horizontalLayout_12.addWidget(self.classesBrowseBtn_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 2, 0, 1, 1)
        self.tabs.addTab(self.settingsTab_2, "")
        self.maintabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1912, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionDelete_Selection = QtWidgets.QAction(MainWindow)
        self.actionDelete_Selection.setObjectName("actionDelete_Selection")
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionFolder)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDelete_Selection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.maintabWidget.setCurrentIndex(2)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vision Data Management"))
        self.browseButton.setText(_translate("MainWindow", "Open File"))
        self.retinaButton.setText(_translate("MainWindow", "Retina Processing Enabled"))
        self.browseFolderButton.setText(_translate("MainWindow", "Open Folder"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Highlighted Frames"))
        self.saveButton.setText(_translate("MainWindow", "Save Changes"))
        self.exportButton.setText(_translate("MainWindow", "Export as..."))
        self.generateButton.setText(_translate("MainWindow", "Generate imagevectors from video"))
        self.browseButton_2.setText(_translate("MainWindow", "Open File"))
        self.browseFolderButton_2.setText(_translate("MainWindow", "Open Folder"))
        self.deleteButton_3.setText(_translate("MainWindow", "Delete"))
        self.saveButton_2.setText(_translate("MainWindow", "Save"))
        self.exportButton_2.setText(_translate("MainWindow", "Export as..."))
        self.generateButton_2.setText(_translate("MainWindow", "Generate images from video"))
        self.labelRecording_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; text-decoration: underline;\">VisionDataManagement</span></p></body></html>"))
        self.produceCorticalButton.setText(_translate("MainWindow", "Produce Cortical Images"))
        self.produceBackprojectedButton.setText(_translate("MainWindow", "Produce Backprojected Images"))
        self.recordButton.setText(_translate("MainWindow", "Start Recording"))
        self.stopRecordButton.setText(_translate("MainWindow", "Stop Recording"))
        self.labelRecording.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#f70004;\">RECORDING...</span></p></body></html>"))
        self.checkUnedited.setText(_translate("MainWindow", "Unedited"))
        self.checkBackprojected.setText(_translate("MainWindow", "Backprojected"))
        self.checkRetina.setText(_translate("MainWindow", "Retina Image"))
        self.label_8.setText(_translate("MainWindow", "Fixation X coord"))
        self.label_12.setText(_translate("MainWindow", "Fixation Y coord"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.startButton.setText(_translate("MainWindow", "Play"))
        self.skipBackButton.setText(_translate("MainWindow", "..."))
        self.skipForwardButton.setText(_translate("MainWindow", "..."))
        self.skipBackButton_3.setText(_translate("MainWindow", "<<"))
        self.skipForwardButton3.setText(_translate("MainWindow", ">>"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.mainpage), _translate("MainWindow", "Capture"))
        self.pauseButton_2.setText(_translate("MainWindow", "Pause"))
        self.startButton_2.setText(_translate("MainWindow", "Play"))
        self.skipBackButton_2.setText(_translate("MainWindow", "..."))
        self.skipForwardButton_2.setText(_translate("MainWindow", "..."))
        self.skipBackButton_4.setText(_translate("MainWindow", "<<"))
        self.skipForwardButton_4.setText(_translate("MainWindow", ">>"))
        self.label_2.setText(_translate("MainWindow", "Delay Between Frames (s)"))
        self.fixationMouseButton.setText(_translate("MainWindow", "Set Fixation Point with Mouse"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.focuspage), _translate("MainWindow", "Main"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.gallerypage), _translate("MainWindow", "Gallery"))
        self.cameraRadio_2.setText(_translate("MainWindow", "Camera"))
        self.videoRadio_2.setText(_translate("MainWindow", "Video"))
        self.browseVideoBtn_2.setText(_translate("MainWindow", "Browse"))
        self.startBtn_2.setText(_translate("MainWindow", "Start"))
        self.tabs.setTabText(self.tabs.indexOf(self.controlsTab_2), _translate("MainWindow", "Controls"))
        self.label_9.setText(_translate("MainWindow", "TensorFlow PB File :"))
        self.pbBrowseBtn_2.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "TensorFlow PBTXT File :"))
        self.pbtxtBrowseBtn_2.setText(_translate("MainWindow", "Browse"))
        self.label_11.setText(_translate("MainWindow", "Class Names :"))
        self.classesBrowseBtn_2.setText(_translate("MainWindow", "Browse"))
        self.tabs.setTabText(self.tabs.indexOf(self.settingsTab_2), _translate("MainWindow", "Settings"))
        self.maintabWidget.setTabText(self.maintabWidget.indexOf(self.tab), _translate("MainWindow", "Classifier"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionDelete_Selection.setText(_translate("MainWindow", "Delete"))

from customwidgets import ClickLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

